#!/bin/bash

if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

while getopts "u:" option; do
	case $option in
		u)
			echo "-u $OPTARG" >&2
			USR=${OPTARG}
			;;
	esac
done

if [ -z ${USR} ]; then
	echo "User argument (-u) not set"
else
	echo "Dezaktywacja subdomeny ${USR}.raspberrypi3.fritz.box z pliku ${USR}.raspberrypi3.fritz.box.conf"
	a2dissite $USR.raspberrypi3.fritz.box.conf
	
	echo "Przeładowanie konfiguracji serwera WWW, aby dezaktywować subdomenę ${USR}.raspberrypi3.fritz.box z pliku ${USR}.raspberrypi3.fritz.box.conf"
	service apache2 reload
	
	echo "Usuwanie pliku ${USR}.raspberrypi3.fritz.box.conf subdomeny ${USR}.raspberrypi3.fritz.box"
	rm -v /etc/apache2/sites-available/$USR.raspberrypi3.fritz.box.conf
	
	echo "deluser -remove-home ${USR}"
	deluser -remove-home $USR
	
	echo "delgroup ${USR}"
	delgroup $USR
fi
