#!/bin/bash

if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

while getopts "u:p:" option; do
	case $option in
		u)
			echo "-u $OPTARG" >&2
			USR=${OPTARG}
			;;
		p)
			echo "-p $OPTARG" >&2
			PASS=${OPTARG}
			;;
	esac
done

if [ -z ${USR} ]; then
	echo "User argument (-u) not set"
else
	if [ -z ${PASS} ]; then
		echo "Password argument (-p) not set"
	else
		# echo "useradd -m $USR -N -G www-data -p $(echo $PASS | openssl passwd -1 -stdin)"
		# useradd -m $USR -N -G www-data -p $(echo $PASS | openssl passwd -1 -stdin)
		# echo "useradd -m $USR -G www-data -p $(echo $PASS | openssl passwd -1 -stdin)"
		# useradd -m $USR -G www-data -p $(echo $PASS | openssl passwd -1 -stdin)
		echo "useradd -m $USR -p $(echo $PASS | openssl passwd -1 -stdin)"
		useradd -m $USR -p $(echo $PASS | openssl passwd -1 -stdin)
		
		echo "adduser www-data ${USR}"
		adduser www-data $USR
		mkdir -v /home/$USR/Web
		# chown -v -R $USR:www-data /home/$USR/Web
		chown -v -R $USR:$USR /home/$USR/Web
		
		echo "Tworzenie pliku ${USR}.raspberrypi3.fritz.box.conf subdomeny ${USR}.raspberrypi3.fritz.box"
		echo "<VirtualHost *:80>
	ServerAdmin $USR@raspberrypi3.fritz.box
	ServerName $USR.raspberrypi3.fritz.box
	ServerAlias www.$USR.raspberrypi3.fritz.box
	DocumentRoot /home/$USR/Web
	ErrorLog \${APACHE_LOG_DIR}/error.log
	CustomLog \${APACHE_LOG_DIR}/access.log combined
</VirtualHost>" > /etc/apache2/sites-available/$USR.raspberrypi3.fritz.box.conf

		echo "Aktywacja subdomeny ${USR}.raspberrypi3.fritz.box z pliku ${USR}.raspberrypi3.fritz.box.conf"
		a2ensite $USR.raspberrypi3.fritz.box.conf
		
		echo "Przeładowanie konfiguracji serwera WWW, aby aktywować subdomenę ${USR}.raspberrypi3.fritz.box z pliku ${USR}.raspberrypi3.fritz.box.conf"
		service apache2 reload
	fi
fi
